<a href="https://colab.research.google.com/github/KRiver28/prac/blob/master/numpy_0121.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a =np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# 슬라이싱

In [3]:
a[0:2,0:4]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# 인덱싱

In [5]:
a[0,0]

0

In [6]:
a[0][0]

0

In [7]:
a[[0,2],]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [9]:
 a[:,[0,1,3]]

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

In [10]:
b=100
b=a[0,0]
a[0,0],b

(0, 0)

In [11]:
c=a[1:3,1:3]
c[0,0]=100
c

array([[100,   6],
       [  9,  10]])

In [12]:
a

array([[  0,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9,  10,  11]])

In [13]:
#인덱싱은 원본 데이터에서 값을 복사하여 가져온다 (원본 변화 x)
#슬라이싱은 원본 데이터의 일부를 잘라서 가져온다 (원본 변화 o)

#불리언

In [14]:
a = np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
bool_idx =(a>2)
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [17]:
a[bool_idx]

array([3, 4, 5, 6])

#정수 인덱싱

In [20]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a[[0,1,2],[0,1,0]]

array([1, 4, 5])

In [24]:
np.array([a[0,0],a[1,1],a[2,0]])

array([1, 4, 5])

In [23]:
a[[0,0],[1,1]]
# 행, 열의 자룔를 인덱싱 하여 행렬로 나타냄

array([2, 2])

#Transpose 전치

In [29]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [30]:
x.T

array([[1, 3],
       [2, 4]])

In [31]:
v = np.array([1,2,3,])
v

array([1, 2, 3])

In [32]:
v.T

array([1, 2, 3])

In [35]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [36]:
np.arange(6).reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [38]:
a=np.arange(6).reshape((3,2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
np.reshape(a,(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
np.reshape(a,6)

array([0, 1, 2, 3, 4, 5])

# 1차원 배열 만들기 ravel, flatten

In [41]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5])

In [44]:
a.ravel()

array([0, 1, 2, 3, 4, 5])

In [45]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [46]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

#Concatenate

In [50]:
a=np.array([[1,2],[3,4]])
b= np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [51]:
b

array([[5, 6]])

In [52]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
np.concatenate((a,b.T),axis=1)
#b.T로 b를 전치해줘야한다. 열방향으로 shape을 맞춰주기 위함

array([[1, 2, 5],
       [3, 4, 6]])

In [57]:
a[0:1].T

array([[1],
       [2]])

In [61]:
x =np.array([[1.,2.],[3.,4.]])
y =np.array([[5.,6.],[7.,8.]])
print(x)
print(y)
x+y

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


array([[ 6.,  8.],
       [10., 12.]])

In [63]:
np.sqrt(x) 
#제곱근 연산

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [64]:
x =np.array([[1.,2.],[3.,4.]])
y =np.array([[5.,6.],[7.,8.]])

v =np.array([[9.,10.],[11.,12.]])
w =np.array([[13.,14.],[15.,16.]])

In [68]:
#dot 내적
v.dot(w)

array([[267., 286.],
       [323., 346.]])

In [66]:
np.dot(v,w)

array([[267., 286.],
       [323., 346.]])

In [67]:
x.dot(v)

array([[31., 34.],
       [71., 78.]])

#브로드캐스트

In [98]:
x=np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
#초기화 되지 않고 같은 shpae을 가지는 행렬 만들기
y=np.empty_like(x)
y

array([[     94323349862688,                  50,                   0],
       [                  0,                   0, 7362941623697827179],
       [3256159943067394913, 3630803094119526457, 7290545164355972452],
       [4122307919396222817, 8386112019185951285,               29557]])

In [100]:
v= np.array([1,0,1])
v

array([1, 0, 1])

In [89]:
x.shape

(3, 3)

In [91]:
v.shape

(3,)

In [102]:
for i in range(4):
  y[i,:] =x[i,:]+v

y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [103]:
v

array([1, 0, 1])

In [104]:
vv=np.tile(v,(4,1))
#v행렬을 4번 쌓아서 만드시오
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [106]:
 y= x+vv
 y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [115]:
y = x+v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

#numpy_Quiz

In [123]:
#1번 2*2, 행렬을 만들고 초기화 되지 않은 상태로 배열만들기
q1=np.empty((2,2),dtype=int)
q1

array([[4621256167635550208, 4621819117588971520],
       [4622382067542392832, 4622945017495814144]])

In [126]:
#2번  동일한 shpae의 다차원 배열 만들기 초기화x
x = np.array([[1,2,3],[4,5,6]],np.int32)
q2=np.empty_like(x)
q2

array([[1573026496,      21961,          0],
       [         0,          0,          0]], dtype=int32)

In [132]:
#3번 크기가 3인 단위행렬 만들기 2가지방법
q3_1= np.identity((3))
q3_2= np.eye(3,3)
print(q3_1,'\n\n',q3_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [133]:
#4번 원소가 모두 1인 3*2 행렬 만들기
q4 = np.ones((3, 2))
q4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [134]:
#5번 원소가 모두 1인 x와 shape이 같은 행렬 만들기
x=np.arange(4)
q5 = np.ones_like(x)
q5

array([1, 1, 1, 1])

In [136]:
#6번 3*2 영행렬 만들기
q6 = np.zeros(3*2)
q6

array([0., 0., 0., 0., 0., 0.])

In [138]:
#7번 x와 shpae이 같은 영행렬 만들기
q7 = np.zeros_like(x)
q7

array([0, 0, 0, 0])

In [144]:
#8번 모든 원소가 7인 2*5 배열만들기 2가지
q8_1=np.full((2,5),7)
q8_2=np.ones((2,5))*7
print(q8_1,'\n','\n',q8_2)

[[7 7 7 7 7]
 [7 7 7 7 7]] 
 
 [[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [145]:
#9번 모든 원소가 7인 x와 shape이 같은 배열 만들기 2가지
q9_1=np.full_like(x,7)
q9_2=np.ones_like(x)*7
print(q9_1,'\n','\n',q9_2)

[7 7 7 7] 
 
 [7 7 7 7]


In [147]:
#10번 array 만들기
q10 = np.array([1, 2, 3])
q10

array([1, 2, 3])

In [148]:
#11번 리스트에서 array만들기 (float)
q11=np.array([1, 2, 3,] ,dtype=float)
q11

array([1., 2., 3.])

In [152]:
#12번 1~100 짝수로 된 배열 생성
q12 = np.arange(2,101,2)
q12

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [153]:
#13번 3.0~10.0까지 50개의 원소를 균일하게 만들기
q13=np.linspace(3.0, 10.0, 50)
q13

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [160]:
#14번 열이 150개인 2차원 행렬만들기
x= np.ones((10,10,3))
q14= x.reshape(2,150)
q14

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

In [161]:
#15번 1차원 배열 만들기 3가지
x = np.array([[1,2,3],[4,5,6]])
x.ravel()
x.flatten()

array([1, 2, 3, 4, 5, 6])

In [162]:
#16번 배열 합치기 → [1,2,3,7,8,9],[4,5,6,11,12,13]
x= np.array([[1,2,3],[4,5,6]])
y= np.array([[7,8,9],[10,11,12]])

np.concatenate((x, y), axis = 1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [163]:
#17번 [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
q17=np.concatenate((x, y), axis = 0)
q17


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [168]:
#18번 아래x를 가지고 [0,0,1,1,2,2]인 배열 만들기
x= np.array([0,1,2])
q18=np.sort(np.tile(x, 2))

q18

array([0, 0, 1, 1, 2, 2])

In [165]:
#19번 아래x에서 앞,뒤의 0을 제거

In [171]:
x=np.array([0,0,0,1,2,3,0,2,1,0])
q19=x[3:-1]
q19

array([1, 2, 3, 0, 2, 1])