<a href="https://colab.research.google.com/github/KRiver28/prac/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
score1 =11
score2 =12
score3 =13
score4 =14

sum =score1+ score2 +score3
avg = sum/3

sum,avg

(36, 12.0)

In [7]:
scoreList = [11,12,13,14]
sumList=0
avgList=0

for score in scoreList:
  sumList += score

avgList = sumList / len(scoreList)

sumList, avgList

(50, 12.5)

In [8]:
scoreList2 = []
for score in scoreList:
  scoreList2.append(score+1)

scoreList2


[12, 13, 14, 15]

In [11]:
#scoreList에서 각각 10점을 올려준다
scoreList3 = []
for score in scoreList:
  scoreList3.append(score+10)

scoreList3

[21, 22, 23, 24]

In [14]:
#List Comprehension 활용해서 위 문제 풀어보기
scoreList3 = [(score+10)for score in scoreList]
scoreList3

[21, 22, 23, 24]

In [15]:
# 2차원 list 만들기
lst=[[1,2,3],
     [4,5,6],
     [7,8,9]
     ]


In [179]:
# 2차원 리스트의 각 요소에 1 더하기
lst2=[(i+1) for i in lst]
lst2

TypeError: ignored

In [58]:
lst=[[1,2,3],
     [4,5,6],
     [7,8,9]
     ]

lst2 =[]

for i in range(len(lst)):
  lst_in =[]
  for j in range(len(lst[i])):
    lst_in.append(lst[i][j] +1)
  lst2.append(lst_in)
lst2




[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [40]:
for i in range(len(lst)):
  for j in range(len(lst[i])):
    lst[i][j] += 1


[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [68]:
import numpy as np
scoreNdarray = np.array(lst)
scoreNdarray
array=([1,2,3],
      [4,5,6],
      [7,8,9])
scoreNdarray+1




array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [64]:
np.sum(scoreNdarray)

45

In [65]:
np.mean(scoreNdarray)

5.0

In [74]:
np.mean(scoreNdarray,axis=0)
#axis=0일경우 행 방향


array([4., 5., 6.])

In [70]:
scoreNdarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
np.mean(scoreNdarray,axis=1)
#axis=1일경우 열 방향

array([2., 5., 8.])

In [77]:
#2차원 랜덤값 받기 2*2 행렬
sample2D=np.random.rand(2,2)
sample2D

array([[0.96343611, 0.15997695],
       [0.97746764, 0.04028694]])

In [82]:
#랜덤값으로 리스트 만들기
sample2Dlist= sample2D.tolist()
sample2Dlist

[[0.9634361142821287, 0.15997695238558263],
 [0.9774676384457034, 0.04028694243176434]]

In [86]:
#sum 계산하는데 걸리는 시간
import datetime
sum = 0
start=datetime.datetime.now()
for rows in sample2Dlist:
  for e in rows:
    sum+=e

print(sum)
datetime.datetime.now()-start

2.141167647545179


datetime.timedelta(microseconds=1107)

In [88]:
sample2Darray=np.random.rand(100,100)
sample2Dlist = sample2Darray.tolist()
sample2Dlist

[[0.1367845909603128,
  0.48140285942877037,
  0.07391718109771273,
  0.4441936665109819,
  0.9981653185965397,
  0.3393821225707342,
  0.371897588263466,
  0.739023658122816,
  0.22505221661339847,
  0.6591507701881171,
  0.15082298816356876,
  0.39787268580233615,
  0.5146469781219006,
  0.15093412444191534,
  0.04201645036487922,
  0.20561315043880823,
  0.23246411727493022,
  0.4436849880763536,
  0.22740349143494787,
  0.1263045141938327,
  0.58448709812145,
  0.6989788879203308,
  0.7192110668354864,
  0.5854844792216217,
  0.5056856265803894,
  0.7377561908025664,
  0.11341875482174657,
  0.2990423946904779,
  0.08094675205732138,
  0.23024878682321004,
  0.36655826199947306,
  0.4537436843841556,
  0.9169124101476427,
  0.4365309424729875,
  0.07636745590885408,
  0.19743140471665,
  0.8880586838474487,
  0.286988707977067,
  0.08294638549292144,
  0.4966633552338773,
  0.02625981206038719,
  0.006868663788046181,
  0.03223309613543279,
  0.7956154089930702,
  0.687303309285311

In [99]:
 x= np.array([[1,2],[3,4]], dtype=np.int8)
 x

array([[1, 2],
       [3, 4]], dtype=int8)

In [92]:
y=x.T
y

array([[1, 3],
       [2, 4]], dtype=int8)

In [100]:
x.strides

(2, 1)

In [94]:
y.strides

(1, 2)

In [101]:
np.mean(range(1,11))

5.5

In [102]:
#가중평균
np.average(range(1,11),weights=range(10,0,-1))

4.0

In [103]:
intarray= np.array([[1,2],[3,4]])
intarray

array([[1, 2],
       [3, 4]])

In [104]:
intarray.dtype

dtype('int64')

In [107]:
uintarray =np.array([[1,2],[3,4]], dtype='uint')
uintarray


array([[1, 2],
       [3, 4]], dtype=uint64)

In [109]:
floatarray = np.array([[1.,2.],[3.,4.]])
floatarray

array([[1., 2.],
       [3., 4.]])

In [110]:
floatarray.dtype

dtype('float64')

In [111]:
!wget -O 'mnist_train.csv' https://pjreddie.com/media/files/mnist_train.csv


/bin/bash: wget -O mnist_train.csv https://pjreddie.com/media/files/mnist_train.csv: No such file or directory


In [113]:
fromCSVArray = np.genfromtxt('mnist_train.csv',delimiter=',')

ValueError: ignored

In [114]:
np.empty((4,3))

array([[4.67686710e-310, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.74084271e+169],
       [5.64400532e-091, 4.27629916e-033, 2.34116811e-057],
       [2.58155563e-057, 3.99910963e+252, 1.46030983e-319]])

In [115]:
A =np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])


In [116]:
np.empty_like(A)
#empty 행렬을 만들며, A의 형태로 만든다 (4행3렬로 만든다)

array([[     94660844030112,                  50, 7146768841584043371],
       [3256776738318005092, 4122539877641511992, 3759771461617855793],
       [3760563303210168375, 8386112019185612852,               29557]])

In [117]:
np.zeros((2,3))
#0으로 된 2행 3렬짜리 어레이를 만든다

array([[0., 0., 0.],
       [0., 0., 0.]])

In [118]:
np.ones((2,3))
# 2행 3렬로 1을 채운다

array([[1., 1., 1.],
       [1., 1., 1.]])

In [119]:
np.identity((2))
#항등행렬을 나타낸다 (2행2열) 

array([[1., 0.],
       [0., 1.]])

In [124]:
np.eye(3,4,1)


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [126]:
np.full((2,3),10)
# 2행3열을 10으로 채운다.

array([[10, 10, 10],
       [10, 10, 10]])

In [128]:
10*np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [132]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.arange(1.0,5.0,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [130]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [135]:
#axis =0 이면 행방향!
#axis =1 이면 열방향!

In [139]:
A =np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [141]:
np.amin(A,axis=0)

array([0, 1])

In [142]:
np.amin(A,axis=1)

array([0, 2])

In [143]:
np.amax(A,axis=0)

array([2, 3])

In [148]:
B=np.arange(9).reshape(3,3)
np.amin(B,axis=0)

array([0, 1, 2])

In [150]:
np.ptp(A,axis=0)
#최대값에서 최소값을 뺀 것

array([2, 2])

In [151]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [154]:
np.median(B,axis=0)
#중간 값

array([3., 4., 5.])

In [156]:
np.mean(B,axis=0)

array([3., 4., 5.])

In [157]:
#분산 구하기
np.var(B,axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [158]:
#표준편차 구하기
np.std(B,axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [161]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
a[0:2,0:4]
#0번째 행부터 1번째 행까지 + 0번쨰 열부터 3번째 열까지 슬라이싱

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [165]:
a[:2,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [166]:
a[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [167]:
a[0,0]

0

In [168]:
a[[0,2],]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [170]:
sRow=a[0:1,:]
sRow

array([[0, 1, 2, 3]])

In [171]:
sRow.shape

(1, 4)

In [177]:
 #sRow가 몇차원인지 확인
 sRow.ndim

2

In [173]:
iRow=a[0]
iRow

array([0, 1, 2, 3])

In [174]:
iRow.shape

(4,)

In [176]:
iRow.ndim

1

In [178]:
sliced =a[:,0:1]
sliced

array([[0],
       [4],
       [8]])